(function(g){var window=this;var uAa=function(a,b,c,d){var e=b.oc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.qd(c,d?d:"mqdefault.jpg");var k=b instanceof g.XN?g.AV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.uQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.XN?b.ya:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.Pm||g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Rn(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.wQ&&(c.playlist_length=b.getLength());a.update(c)},v5=function(a,b){g.CI.call(this,{G:"div",
ba:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},w5=function(a){var b={G:"span",
L:"ytp-upnext-top",J:[{G:"span",L:"ytp-upnext-header",J:[g.U("YTP_PLAYLIST_UP_NEXT")]},{G:"span",L:"ytp-upnext-title",J:["{{title}}"]},{G:"span",L:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={G:"div",L:"ytp-upnext",U:{"aria-label":"{{aria_label}}"},J:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},b,{G:"a",L:"ytp-upnext-autoplay-icon",U:c,J:[{G:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
J:[{G:"circle",L:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",J:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
J:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]}]};g.V.call(this,b);this.A=null;b=this.sa["ytp-upnext-cancel"];this.A=new g.V({G:"button",ba:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":g.U("YTP_AUTOPLAY_CANCEL")},J:[g.U("YTP_CANCEL")]});g.L(this,this.A);this.A.T("click",this.FP,this);this.A.va(b);this.l=a;this.I=this.sa["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.F=new g.Zt(this.hn,5E3,this);g.L(this,this.F);this.H=0;this.O(this.sa["ytp-upnext-autoplay-icon"],"click",
this.QR);this.FB();this.O(a,"autonavvisibility",this.FB);this.O(a,"mdxnowautoplaying",this.eR);this.O(a,"mdxautoplaycanceled",this.fR);this.O(a,"mdxautoplayupnext",this.lE);3==this.l.Ua()&&(a=(a=g.NU(g.IU(this.l)))?a.JI():null)&&this.lE(a)},vAa=function(a,b){a.B=b;
uAa(a,b,g.X(a.l),"hqdefault.jpg")},x5=function(a,b){if(!a.o){g.aG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title);
a.H=g.lG();a.o=new g.Zt((0,g.z)(a.lq,a,b),25);a.lq(b);var c=b||g.X(a.l).experiments.l("autoplay_time")||1E4;a.l.ua("onAutonavCoundownStarted",c)}g.uq(a.element,"ytp-upnext-autoplay-paused")},z5=function(a){y5(a);
a.H=g.lG();a.lq();g.S(a.element,"ytp-upnext-autoplay-paused")},y5=function(a){a.o&&(a.o.dispose(),a.o=null)},A5=function(a,b){b=void 0===b?!1:b;
var c=g.X(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.WU(a.l,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.oc(),a.hn(),a.C=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.qd(c)}),a.D=a.O(a.C,"click",a.GR),a.F.start())}y5(a);a.l.Tj(!1,b)},wAa=function(a){v5.call(this,a,"subscribecard-endscreen");
var b=a.ea();this.o=new g.V({G:"div",L:"ytp-subscribe-card",J:[{G:"img",L:"ytp-author-image",U:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",J:[{G:"div",L:"ytp-author-name",J:[b.author]},{G:"div",L:"html5-subscribe-button-container"}]}]});g.L(this,this.o);this.o.va(this.element);this.A=new g.g_(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.fm,b.subscribed,"trailer-endscreen",null,null,a);g.L(this,this.A);this.A.va(this.o.sa["html5-subscribe-button-container"]);this.hide()},
B5=function(a){var b=g.X(a),c=g.DH||g.gf?{style:"will-change: opacity"}:void 0,d=b.l&&!b.isDni,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",ba:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",L:"ytp-videowall-still-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",J:[{G:"span",L:"ytp-videowall-still-info-bg",J:[{G:"span",L:"ytp-videowall-still-info-content",U:c,J:[{G:"span",L:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",
L:"ytp-videowall-still-info-author",J:["{{author_and_views}}"]},{G:"span",L:"ytp-videowall-still-info-live",J:[g.U("YTP_LIVE")]},{G:"span",L:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",ba:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",ba:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.A=d;this.o=a;this.l=null;this.T("click",this.B);this.T("keypress",this.C);g.X(a).M&&(a=a.app.da,b=this.element,g.Qa(a.g,b),g.Ta(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.bf(this,(0,g.z)(a.D,a,b)))},C5=function(a){v5.call(this,a,"videowall-endscreen");
this.M=a;this.F=0;this.A=[];this.H=this.D=this.C=null;this.I=this.P=!1;this.B=new g.JF(this);g.L(this,this.B);this.K=new g.Zt(g.Fa(g.S,this.element,"ytp-show-tiles"),0);g.L(this,this.K);var b=new g.V({G:"button",ba:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":g.U("YTP_PREVIOUS")},J:[g.Ooa()]});g.L(this,b);b.va(this.element);b.T("click",this.GN,this);this.N=new g.wI({G:"div",L:"ytp-endscreen-content"});g.L(this,this.N);this.N.va(this.element);b=new g.V({G:"button",ba:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":g.U("YTP_NEXT")},J:[g.Poa()]});g.L(this,b);b.va(this.element);b.T("click",this.FN,this);this.o=new w5(a);g.L(this,this.o);g.gV(this.l,this.o.element,4);this.hide()},D5=function(a){return g.hV(a.l)&&a.pq()&&!a.H},xAa=function(a,b){return(0,g.G)(b.suggestions,function(b){b=g.VY(b);
g.L(a,b);return b})},E5=function(a){var b=a.At();
b!=a.P&&(a.P=b,a.l.R("autonavvisibility"))},F5=function(a){g.mV.call(this,a);
g.XG({YTP_AUTOPLAY_CANCEL:"Cancel autoplay",YTP_AUTOPLAY_NEXT:"Play next video",YTP_AUTOPLAY_PAUSED_3:"Autoplay is paused",YTP_CANCEL:"Cancel",YTP_MIX:"Mix",YTP_PLAYLIST_UP_NEXT:"Up Next",YTP_UNSUBSCRIBE:"Unsubscribe"});this.l=null;this.o=new g.JF(this);g.L(this,this.o);this.A=g.X(a);yAa(a)?this.l=new C5(this.g):this.A.aa?this.l=new wAa(this.g):this.l=new v5(this.g);g.L(this,this.l);g.gV(this.g,this.l.element,4);this.XC();this.o.O(a,"videodatachange",this.XC,this);this.o.O(a,"crn_endscreen",this.HL,
this);this.o.O(a,"crx_endscreen",this.IL,this)},yAa=function(a){a=g.X(a);
return a.Oc&&!a.aa};
g.p(v5,g.CI);v5.prototype.create=function(){this.created=!0};
v5.prototype.destroy=function(){this.created=!1};
v5.prototype.pq=function(){return!1};
v5.prototype.At=function(){return!1};g.p(w5,g.V);g.h=w5.prototype;g.h.hn=function(){this.C&&(this.F.stop(),this.Ba(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.FB=function(){g.BI(this,g.JU(this.l))};
g.h.GR=function(){window.focus();this.hn()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.lq=function(a){a=a||g.X(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.lG()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.Ua()?A5(this,!0):this.o&&this.o.start()};
g.h.QR=function(a){!g.Rd(this.A.element,g.yF(a))&&g.gX(a,this.l)&&A5(this)};
g.h.FP=function(){g.LU(this.l,!0)};
g.h.eR=function(a){this.l.Ua();this.show();x5(this,a)};
g.h.lE=function(a){this.l.Ua();this.B&&this.B.oc().videoId==a.oc().videoId||vAa(this,a)};
g.h.fR=function(){this.l.Ua();y5(this);this.hide()};
g.h.V=function(){y5(this);this.hn();g.V.prototype.V.call(this)};g.p(wAa,v5);g.p(B5,g.V);B5.prototype.ik=function(){g.kV(this.o,this.element);var a=this.l.oc().videoId,b=this.l.getPlaylistId();g.h0(this.o.app,a,this.l.ee,b,void 0,void 0,void 0)};
B5.prototype.B=function(a){g.gX(a,this.o,this.A,this.l.ee||void 0)&&this.ik()};
B5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.DF(a)||(this.ik(),g.CF(a))}};g.p(C5,v5);g.h=C5.prototype;g.h.create=function(){v5.prototype.create.call(this);var a=this.l.ea();a&&(this.C=xAa(this,a),this.D=a);this.Hg();this.B.O(this.l,"appresize",this.Hg);this.B.O(this.l,"onVideoAreaChange",this.Hg);this.B.O(this.l,"videodatachange",this.HN);this.B.O(this.l,"autonavchange",this.FA);this.B.O(this.l,"autonavcancel",this.EN);this.B.O(this.element,"transitionend",this.fT)};
g.h.destroy=function(){g.LF(this.B);g.df(this.A);this.A=[];this.C=null;v5.prototype.destroy.call(this);g.uq(this.element,"ytp-show-tiles");this.K.stop()};
g.h.pq=function(){return 1!=this.D.autonavState};
g.h.show=function(){v5.prototype.show.call(this);g.uq(this.element,"ytp-show-tiles");g.X(this.l).g?g.au(this.K):this.K.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.LU(this.l,!1);var a=D5(this);g.hV(this.l)&&g.X(this.l).experiments.g("ui_logging")&&g.WU(this.l,"end",{cancelButtonShow:a?"1":"0",state:this.pq()?"enabled":"disabled"});a?(E5(this),2==this.D.autonavState?g.X(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.Di()?A5(this.o,!0):x5(this.o):3==this.D.autonavState&&
z5(this.o)):(g.LU(this.l,!0),E5(this))};
g.h.hide=function(){v5.prototype.hide.call(this);z5(this.o);E5(this)};
g.h.fT=function(a){g.yF(a)==this.element&&this.Hg()};
g.h.Hg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.ZU(this.M,!0),b=g.QI(this.M);b&&(b=b.sd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,C=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&C)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(C)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.cd(a.width/m||1,1,1.21);n*=g.cd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Kh(a,m,n);g.sh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});vAa(this.o,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",D5(this));E5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),q=g.dd(q+this.F,l),0!=r){u=this.A[c];u||(u=new B5(this.l),this.A[c]=u,a.appendChild(u.element));C=Math.floor(n*k/e);var I=Math.floor(m*f/b),O=Math.floor(n*(k+r)/e)-C-4,ca=Math.floor(m*(f+r)/b)-I-4;g.zh(u.element,I,C);g.Kh(u.element,ca,O);g.sh(u.element,"transitionDelay",(k+f)/20+"s");g.T(u.element,"ytp-videowall-still-mini",1==r);g.T(u.element,"ytp-videowall-still-large",2<r);r=u;q=this.C[q];r.l!=q&&(r.l=q,uAa(r,q,g.X(r.o),g.sq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),u=(q=q.ee)&&q.itct)&&(q=r.o,g.X(q).M&&(q=q.app.da,r=r.element,C=r.getAttribute("data-visual-id"),g.Qa(q.g,r),g.iV(q,"onLogServerVeCreated",{id:C,tracking_params:u})));c++}g.T(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Kd(e.element),g.cf(e);this.A.length=c}};
g.h.HN=function(){var a=this.l.ea();this.D!=a&&(this.F=0,this.C=xAa(this,a),this.D=a,this.Hg())};
g.h.FN=function(){this.F+=this.A.length;this.Hg()};
g.h.GN=function(){this.F-=this.A.length;this.Hg()};
g.h.MK=function(){return!!this.o.o};
g.h.FA=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,y5(this.o),this.g&&this.Hg()):(this.I=!0,this.g&&D5(this)&&(2==a?x5(this.o):3==a&&z5(this.o)))};
g.h.EN=function(a){if(a){for(a=0;a<this.A.length;a++)g.lV(this.M,this.A[a].element,!0);this.FA(1)}else this.H=null,this.I=!1;this.Hg()};
g.h.At=function(){return this.g&&D5(this)};g.p(F5,g.mV);g.h=F5.prototype;g.h.fA=function(){var a=this.g.ea(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!yAa(this.g)||b;a=g.qO(a,"ypc_module");var c=g.i0(this.g.app);return b&&!a&&!c};
g.h.eA=function(){return this.l.At()};
g.h.IK=function(){return this.eA()?this.l.MK():!1};
g.h.V=function(){g.eV(this.g,"endscreen");g.mV.prototype.V.call(this)};
g.h.load=function(){g.mV.prototype.load.call(this);this.l.show();g.X(this.g).aa&&.01>Math.random()&&g.WU(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.mV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.HL=function(a){this.fA()&&(this.l.created||this.l.create(),"load"==a.ka&&this.load())};
g.h.IL=function(a){"load"==a.ka&&this.loaded&&this.unload()};
g.h.XC=function(){g.eV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ea().lengthSeconds-10),0);a=new g.rQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.L(this,a);var b=new g.rQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.L(this,b);g.bV(this.g,[a,b])};g.aY.endscreen=F5;})(_yt_player);
